//use when local
export const initLifeExpectancy = `http://localhost:3001/api/initLifeExpectancy`
export const getLifeExpectancy = `http://localhost:3001/api/getLifeExpectancy`
export const initAlcoholTobaccoData = `http://localhost:3001/api/initAlcoholTobaccoData`
export const getAlcoholTobaccoData = `http://localhost:3001/api/getAlcoholTobaccoData`
export const initDCData = `http://localhost:3001/api/initDCData`
export const getDCData = `http://localhost:3001/api/getDCData`
export const initNAWData = `http://localhost:3001/api/initNAWData`
export const getNAWData = `http://localhost:3001/api/getNAWData`
export const initUSPopulationData = `http://localhost:3001/api/initUSPop`
export const getUSPopulationData = `http://localhost:3001/api/getUSPop`
export const initCDSummaryData = `http://localhost:3001/api/initCDSummary`
export const getCDSummaryData = `http://localhost:3001/api/getCDSummary`
export const initWeightSummary = `http://localhost:3001/api/initWeight`
export const getWeightSummary = `http://localhost:3001/api/getWeight`
export const initUninsuredSummary = `http://localhost:3001/api/initUninsuredUSPop`
export const getUninsuredSummary = `http://localhost:3001/api/getUninsuredUSPop`
export const initUninsuredByEducation = `http://localhost:3001/api/initUninsuredByEducation`
export const getUninsuredByEducation = `http://localhost:3001/api/getUninsuredByEducation`
export const initUninsuredByAge = `http://localhost:3001/api/initUninsuredByAge`
export const getUninsuredByAge = `http://localhost:3001/api/getUninsuredByAge`
export const initUninsuredBySubgroup = `http://localhost:3001/api/initUninsuredBySubgroup`
export const getUninsuredBySubgroup = `http://localhost:3001/api/getUninsuredBySubgroup`
export const initBirthRateData = `http://localhost:3001/api/initBirthRateData`
export const getBirthRateData = `http://localhost:3001/api/getBirthRateData`
export const initGestBirthRates = `http://localhost:3001/api/initGestBirthRates`
export const getGestBirthRates = `http://localhost:3001/api/getGestBirthRates`
export const init12MonthBirthRates = `http://localhost:3001/api/initLast12MonthBirthData`
export const get12MonthBirthRates = `http://localhost:3001/api/getLast12MonthBirthData`



//use in VM
// export const initLifeExpectancy = `http://healthdashboard.mitre.org/api/initLifeExpectancy`
// export const getLifeExpectancy = `http://healthdashboard.mitre.org/api/getLifeExpectancy`
// export const initAlcoholTobaccoData = `http://healthdashboard.mitre.org/api/initAlcoholTobaccoData`
// export const getAlcoholTobaccoData = `http://healthdashboard.mitre.org/api/getAlcoholTobaccoData`
// export const initDCData = `http://healthdashboard.mitre.org/api/initDCData`
// export const getDCData = `http://healthdashboard.mitre.org/api/getDCData`
// export const initNAWData = `http://healthdashboard.mitre.org/api/initNAWData`
// export const getNAWData = `http://healthdashboard.mitre.org/api/getNAWData`
// export const initUSPopulationData = `http://healthdashboard.mitre.org/api/initUSPop`
// export const getUSPopulationData = `http://healthdashboard.mitre.org/api/getUSPop`
// export const initCDSummaryData = `http://healthdashboard.mitre.org/api/initCDSummary`
// export const getCDSummaryData = `http://healthdashboard.mitre.org/api/getCDSummary`
// export const initWeightSummary = `http://healthdashboard.mitre.org/api/initWeight`
// export const getWeightSummary = `http://healthdashboard.mitre.org/api/getWeight`
// export const initUninsuredSummary = `http://healthdashboard.mitre.org/api/initUninsuredUSPop`
// export const getUninsuredSummary = `http://healthdashboard.mitre.org/api/getUninsuredUSPop`
// export const initUninsuredByEducation = `http://healthdashboard.mitre.org/api/initUninsuredByEducation`
// export const getUninsuredByEducation = `http://healthdashboard.mitre.org/api/getUninsuredByEducation`
// export const initUninsuredByAge = `http://healthdashboard.mitre.org/api/initUninsuredByAge`
// export const getUninsuredByAge = `http://healthdashboard.mitre.org/api/getUninsuredByAge`
// export const initUninsuredBySubgroup = `http://healthdashboard.mitre.org/api/initUninsuredBySubgroup`
// export const getUninsuredBySubgroup = `http://healthdashboard.mitre.org/api/getUninsuredBySubgroup`
// export const initBirthRateData = `http://healthdashboard.mitre.org/api/initBirthRateData`
// export const getBirthRateData = `http://healthdashboard.mitre.org/api/getBirthRateData`
// export const initGestBirthRates = `http://healthdashboard.mitre.org/api/initGestBirthRates`
// export const getGestBirthRates = `http://healthdashboard.mitre.org/api/getGestBirthRates`
// export const init12MonthBirthRates = `http://healthdashboard.mitre.org/api/initLast12MonthBirthData`
// export const get12MonthBirthRates = `http://healthdashboard.mitre.org/api/getLast12MonthBirthData`
